### ISSUE TITLE
ImportError: cannot import name 'compose' from 'cx' (/home/server03/anaconda3/envs/c/lib/python3.9/site-packages/cx/__init__.py)

### ISSUE THREAD

**Issue by Baobaon** [wysoczanska/clip_dinoiser#20]
Traceback (most recent call last):  File "/data/server03/Zhaozikai/clip_dinoiser-main/demo.py", line 2, in <module>
    from models.builder import build_model
  File "/data/server03/Zhaozikai/clip_dinoiser-main/models/__init__.py", line 1, in <module>
    from .maskclip import *
  File "/data/server03/Zhaozikai/clip_dinoiser-main/models/maskclip/__init__.py", line 1, in <module>
    from .maskclip import *
  File "/data/server03/Zhaozikai/clip_dinoiser-main/models/maskclip/maskclip.py", line 15, in <module>
    from open_clip import get_tokenizer,  create_model_from_pretrained
  File "/home/server03/anaconda3/envs/c/lib/python3.9/site-packages/open_clip/__init__.py", line 1, in <module>
    from .coca_model import CoCa
  File "/home/server03/anaconda3/envs/c/lib/python3.9/site-packages/open_clip/coca_model.py", line 9, in <module>
    from .transformer import (
  File "/home/server03/anaconda3/envs/c/lib/python3.9/site-packages/open_clip/transformer.py", line 11, in <module>
    from .utils import to_2tuple
  File "/home/server03/anaconda3/envs/c/lib/python3.9/site-packages/open_clip/utils.py", line 6, in <module>
    from torchvision.ops.misc import FrozenBatchNorm2d
  File "/home/server03/anaconda3/envs/c/lib/python3.9/site-packages/torchvision/__init__.py", line 7, in <module>
    from torchvision import models
  File "/home/server03/anaconda3/envs/c/lib/python3.9/site-packages/torchvision/models/__init__.py", line 16, in <module>
    from . import detection
  File "/home/server03/anaconda3/envs/c/lib/python3.9/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/home/server03/anaconda3/envs/c/lib/python3.9/site-packages/torchvision/models/detection/faster_rcnn.py", line 16, in <module>
    from .anchor_utils import AnchorGenerator
  File "/home/server03/anaconda3/envs/c/lib/python3.9/site-packages/torchvision/models/detection/anchor_utils.py", line 10, in <module>
    class AnchorGenerator(nn.Module):
  File "/home/server03/anaconda3/envs/c/lib/python3.9/site-packages/torchvision/models/detection/anchor_utils.py", line 63, in AnchorGenerator
    device: torch.device = torch.device("cpu"),
/home/server03/anaconda3/envs/c/lib/python3.9/site-packages/torchvision/models/detection/anchor_utils.py:63: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484806139/work/torch/csrc/utils/tensor_numpy.cpp:68.)
  device: torch.device = torch.device("cpu"),
/home/server03/anaconda3/envs/c/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Traceback (most recent call last):
  File "/data/server03/Zhaozikai/clip_dinoiser-main/demo.py", line 3, in <module>
    from cx import compose, initialize
ImportError: cannot import name 'compose' from 'cx' (/home/server03/anaconda3/envs/c/lib/python3.9/site-packages/cx/__init__.py)

**Comment by wysoczanska** [comment]
Hi, could you give some details about the configuration of your env? I'd need some more context to help you solve the issue. Thanks!
