### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by SydCS** [wysoczanska/clip_dinoiser#7]
```
Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    from utils.visualization import mask2rgb
  File "/home/yg/FOUND/clip_dinoiser/utils/__init__.py", line 2, in <module>
    from .visualization import *
  File "/home/yg/FOUND/clip_dinoiser/utils/visualization.py", line 3, in <module>
    def mask2rgb(mask: np.array, palette: list[list]):
TypeError: 'type' object is not subscriptable
```
Should it be `palette: "list[list]"`?

**Comment by wysoczanska** [comment]
Hi, I'm not really sure I understand the problem. I think there was a bug with typing. Can you check if the current version works for you?

**Comment by wysoczanska** [comment]
Closing since there is no reply and others seem to be able to run the demo. Feel free to reopen if the issue persists.
